<?php

namespace Drupal\llm_services\Model;

/**
 * Interface used for completion responses from models.
 */
interface CompletionResponseInterface {

  /**
   * Get the name of the model used.
   *
   * @return string
   *   The name of the module.
   */
  public function getModel(): string;

  /**
   * The response from the model.
   *
   * @return string
   *   The text generated by the model.
   */
  public function getResponse(): string;

  /**
   * The completion status.
   *
   * @return bool
   *   If false, the model has more to say.
   */
  public function getStatus(): bool;

}
